### ISSUE TITLE
Improvement: hide/show other icon's extensions

### ISSUE THREAD

**Issue by KIMWW** [kakakikikeke/compact-toolbar#5]
Thanks for this extension.
Would it be possible to hide/show other icon's extensions which are lodged on bookmark toolbar?

**Comment by kakakikikeke** [comment]
It seems that there is no API that can operate the icon, so it can not be implemented. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks

**Comment by kakakikikeke** [comment]
Sorry, we don't have an API for this yet. It might be possible to do this using userChrome.css, so please try that.

```css
#unified-extensions-button {
  display: none !important;
}

/* Or hide specific extension IDs */
#widget-overflow > toolbarbutton[extensionid="compact-toolbar@example.com"] {
  display: none !important;
}
```
